### ISSUE TITLE
Building error.

### ISSUE THREAD

**Issue by HamzaAnis** [muhammadumerfarooq/-Hotel-Reservation-Class-Librares#2]
![image](https://cloud.githubusercontent.com/assets/18266623/23366826/f8fc05d2-fd29-11e6-955a-3e1e7bdd8e80.png)

This must be due to some untracked files. Make sure to include all the necessary file for the project.

**Comment by muhammadumerfarooq** [comment]
add reference  of .dll file to solution explorer

**Comment by muhammadumerfarooq** [comment]
https://github.com/muhammadumerfarooq/-Hotel-Reservation-Class-Librares
add this file .dll to soltuion explorer
